apiVersion: v1
kind: ReplicationController
metadata:
  name: postgres-v1
  namespace: brightics-hadoop
  labels:
    k8s-app: postgres
    version: v1
    kubernetes.io/cluster-service: "true"
spec:
  replicas: 1
  selector:
    k8s-app: postgres
    version: v1
  template:
    metadata:
      labels:
        k8s-app: postgres
        version: v1
        kubernetes.io/cluster-service: "true"
    spec:
      containers:
        - image: postgres
          name: postgres
      hostNetwork: true
      nodeSelector:
        role: ambari-server 
