apiVersion: v1
kind: ReplicationController
metadata:
  name: ambari-agent-v1
  namespace: brightics-hadoop
  labels:
    k8s-app: ambari-agent
    version: v1
    kubernetes.io/cluster-service: "true"
spec:
  replicas: 1
  selector:
    k8s-app: ambari-agent
    version: v1
  template:
    metadata:
      labels:
        k8s-app: ambari-agent
        version: v1
        kubernetes.io/cluster-service: "true"
    spec:
      containers:
        - image: ambari-agent:1
          name: ambaria
          env:
          - name: AMBARI_MASTER
            value: "ip-10-43-23-82.us-west-2.compute.internal"
      hostNetwork: true
      nodeSelector:
        role: ambari-agent 
